spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8081
          predicates:
            - Path=/users/**

        - id: order-service
          uri: http://localhost:8082
          predicates:
            - Path=/orders/**  # ✅ Removed extra `-`

  application:
    name: gradleproject

  security:
    user:
      name: admin
      password: admin123
    basic:
      enabled: false
    enabled: false

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect

  datasource:
    url: jdbc:h2:file:C:/Users/91998/test/testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: password

  sql:
    init:
      mode: always
      continue-on-error: true

  main:
     web-application-type: reactive  # Forces Spring Boot to use reactive mode
     allow-bean-definition-overriding: true  # ✅ Allow bean override

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

server:
  port: 8100  # ✅ Moved outside of `spring:` block
  servlet:
    context-path: /gradleproject
