spring:


  application:
    name: gradleproject


  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect

  datasource:
    url: jdbc:h2:file:C:/Users/91998/test/testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: password

  sql:
    init:
      mode: always
      continue-on-error: true


server:
  port: 8100  # ✅ Moved outside of `spring:` block
  servlet:
    context-path: /gradleproject
